### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by avaer** [webaverse/xrpackage#54]
We have a bunch of logo designs to choose from. We should add one of these to the repo header.

<img width="606" alt="card2" src="https://user-images.githubusercontent.com/6926057/85185803-a2bca580-b263-11ea-8eb5-68a28c6f3136.PNG">
<img width="670" alt="card3" src="https://user-images.githubusercontent.com/6926057/85185806-a3553c00-b263-11ea-8eb9-91f3d5ef3de3.PNG">
<img width="653" alt="card4" src="https://user-images.githubusercontent.com/6926057/85185807-a3553c00-b263-11ea-9fec-3bdcd100819c.PNG">
<img width="652" alt="card5" src="https://user-images.githubusercontent.com/6926057/85185809-a3553c00-b263-11ea-860d-b0e0e07eb92a.PNG">
<img width="405" alt="card6" src="https://user-images.githubusercontent.com/6926057/85185811-a3553c00-b263-11ea-8a33-43712291c3cd.PNG">
<img width="648" alt="card7" src="https://user-images.githubusercontent.com/6926057/85185812-a3553c00-b263-11ea-8b3a-e2a4994149ca.PNG">
<img width="648" alt="card8" src="https://user-images.githubusercontent.com/6926057/85185813-a3553c00-b263-11ea-8417-4a2587468c5b.PNG">

**Comment by avaer** [comment]
Logo is here: https://github.com/webaverse/xrpackage-site/blob/master/assets/logo.png

We can probably put that in the readme/docs.

**Comment by RangerMauve** [comment]
Those look really cool!
I like the last one most since I find it less busy than the others. 😁
