### ISSUE TITLE
Include puppeteer for screenshot

### ISSUE THREAD

**Issue by avaer** [webaverse/xrpackage#55]
Right now the `xrpk bake` command will hit the https://xrpackage.org/bake.html page in the default browser (using the `open` module).

We need _some_ browser to perform the bake process on packages. However, users have been confused about how this works. A more natural workflow would be to spawn a hidden browser (e.g. puppeteer) and perform the work there rather than in the user's default browser.

This would bloat the install size of xrpk but improve the user experience.

There should probably be a fallback to the default browser for debugging purposes.

**Comment by shu8** [comment]
I think this can be closed since @yahengsu's PR was merged!

**Comment by avaer** [comment]
Indeed 👌 .
