### ISSUE TITLE
Update GIFs to have a transparent background

### ISSUE THREAD

**Issue by shu8** [webaverse/xrpackage#86]
After https://github.com/webaverse/xrpackage-site/pull/20, we'll now be producing transparent background GIFs. It would be nice to update the existing packages to have the transparent background.

**Comment by shu8** [comment]
List of published packages (to track progress) from https://xrpackage.org/browse.html:

- [ ] blob
- [ ] blackchecker.glb
- [ ] booth
- [ ] camera.glb
- [ ] chicken
- [ ] gameboard.glb
- [x] grass
- [ ] grid
- [ ] hololens.glb
- [ ] house.glb
- [ ] kokiri-forest
- [ ] lightsaber
- [ ] meteor
- [ ] miku
- [ ] mirror
- [ ] multiuser.glb
- [ ] nametag
- [ ] photosphere.glb
- [ ] redchecker.glb
- [ ] sword
- [ ] tree
- [ ] vrcrad
- [ ] waft
- [ ] zelda_triforce

**Comment by shu8** [comment]
I couldn't find the source for the following packages:

- blackchecker.glb
- camera.glb
- hololens.glb
- house.glb
- multiuser.glb
- photosphere.glb
- redchecker.glb

**Comment by avaer** [comment]
I think those packages are by @JaredMonkey; I'm not sure about the license to distribute on Github.

However note that it's totally possible to download the packages/models via URL and re-pack them without much trouble, especially for the GLB case.

**Comment by shu8** [comment]
Thanks, I didn't think of downloading the packages and just re-baking them!

I've republished all the packages onto IPFS to have a transparent background now!
