### ISSUE TITLE
Browse page is confusing

### ISSUE THREAD

**Issue by avaer** [webaverse/xrpackage#91]
The browse page is pretty confusing with the inline dropdown links that look like text. I think we need to make the UI portions of the browse page packages much clearer that it's UI.

Screen Shot 2020-07-12 at 6 13 38 AM

Those links should either be buttons or an overlay on top of the package card or something, because they don't seem like links at all. It is also not clear that the package card is clickable into the inspect page. Maybe we don't need these inline links at all, if they are adding to the confusing UI.

One idea is to take the Exokit home page items-inspired design and make packages that simple.

![Screen Shot 2020-07-12 at 6 20 08 AM](https://user-images.githubusercontent.com/6926057/87243896-c52b8400-c407-11ea-80c8-d630660314de.png)

**Comment by avaer** [comment]
There are probably many other designs we could use that aren't confusing. Just pasting design inspirations into this issue would be helpful too.

**Comment by avaer** [comment]
VRoid hub is one inspiration for simple cards: https://hub.vroid.com/tags/256fes

**Comment by shu8** [comment]
How about something like this, removing the download buttons and type (all that info is on the /inspect page anyway)?

![image](https://user-images.githubusercontent.com/8850830/87298881-e755fc80-c502-11ea-87d5-caed1be106e0.png)

**Comment by avaer** [comment]
That looks cleaner -- but maybe we don't need the buttons at all? If the inspect page loads fast and the usage of the package is clear there then we don't need them.

The author it the package and the package type is probably more important than the duplicated "Try"/"Inspect" texts.

**Comment by shu8** [comment]
I made a PR for this at https://github.com/webaverse/xrpackage-site/pull/25 :)
